apiVersion: 1

datasources:
  - name: kniepdennis-neo4j-datasource
    type: kniepdennis-neo4j-datasource
    isDefault: true
    jsonData:
      url: neo4j://neo4j:7687
      database: ""
      username: "neo4j"
    secureJsonData:
      password: "password"
    uid: "adt0ai4d35534a"